services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=animal_adoption_app
    ports:
      - "5455:5432"
    restart: always  